### Buscar por código FIPE

## Codigos FIPE disponiveis aqui: https://www.tabelafipebrasil.com/fipe/carros

GET http://localhost:3000/buscarPorCodigo/004236-6

###

POST http://localhost:3000/gerarArquivo HTTP/1.1
Content-Type: application/json