### Buscar por código FIPE

## Codigos FIPE disponiveis aqui: https://www.tabelafipebrasil.com/fipe/carros

GET http://localhost:3005/buscarPorCodigo/013028-1

###

POST http://localhost:3005/gerarArquivo HTTP/1.1
Content-Type: application/json
