###
POST http://localhost:3000/usuarios/criar HTTP/1.1
Content-Type: application/json

{
    "nome": "Jose Claudio",
    "email": "jose@email.com",
    "senha": "123456"
}

###

GET http://localhost:3000/usuarios/listar 

###
POST http://localhost:3000/usuarios/login HTTP/1.1
Content-Type: application/json

{
    "email": "jose@email.com",
    "senha": "123456"
}

###
POST http://localhost:3000/filmes/criar HTTP/1.1
Content-Type: application/json
Authorization: sabadou

{
    "titulo": "Exterminador do Futuro 2",
    "descricao": "Filme de um robo, bem bacana",
    "categoria": "Ficção Cientifica"
}
###

GET http://localhost:3000/filmes/listar 